kind: ConfigMap
apiVersion: v1
metadata:
  name: ptsagile-config
  namespace: ptsagile-dentun
data:
  spring.datasource.url: jdbc:mysql://192.168.0.164:30032/${pts.database.schema-name}?createDatabaseIfNotExist=true&characterEncoding=UTF-8
  spring.datasource.password: root
  pts.log.path: /app/logs
  eureka.client.service-url.defaultZone: http://ptsagile-service-registry:8061/eureka/
  eureka.client.serviceUrl.defaultZone: http://ptsagile-service-registry:8061/eureka/
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  ptsagile-api-gateway: http://192.168.0.164:30039
  ptsagile-service-registry : http://192.168.0.164:30031
  ptsagile-agile-service: http://192.168.0.164:30033
  pts.pts-core.base-url: http://192.168.0.78:8085/services
