apiVersion: apps/v1
kind: Deployment
metadata:
  name: pts-api-gateway
  namespace: pts-prod
spec:
  selector:
    matchLabels:
      app: pts-api-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: pts-api-gateway
    spec:
      containers:
        - image:  {{DOCKER_IMAGE}}
          name: pts-api-gateway
          ports:
           - containerPort: 8087
          env:
          - name: eureka.client.serviceUrl.defaultZone
            valueFrom:
              configMapKeyRef:
                name: ptsagile-config
                key: eureka.client.service-url.defaultZone
          - name: spring.datasource.url
            valueFrom:
              configMapKeyRef:
                name: ptsagile-config
                key: spring.datasource.url
          - name: spring.datasource.username
            value: "root"
          - name: spring.datasource.password
            valueFrom:
              configMapKeyRef:
                name: ptsagile-config
                key: spring.datasource.password
          - name: pts-api-gateway
            valueFrom:
              configMapKeyRef:
                name: ptsagile-config
                key: pts-api-gateway


---
apiVersion: v1
kind: Service
metadata:
  name: pts-api-gateway
  namespace: pts-prod
spec:
   selector:
    app: pts-api-gateway
   ports:
   - port: 8087
     protocol: TCP
     nodePort: 30001
     targetPort: 8087
   type: LoadBalancer
