apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: pts-service-registry
  namespace: pts-prod
spec:
  selector:
    matchLabels:
      app:  pts-service-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: pts-service-registry
    spec:
      containers:
        - image:  {{DOCKER_IMAGE}}
          name: pts-service-registry
          ports:
           - containerPort: 8061
          env:
          - name: eureka.client.serviceUrl.defaultZone
            valueFrom:
              configMapKeyRef:
                name: ptsagile-config
                key: eureka.client.service-url.defaultZone
          - name: spring.datasource.url
            valueFrom:
              configMapKeyRef:
                name: ptsagile-config
                key: spring.datasource.url
          - name: spring.datasource.username
            value: "root"
          - name: spring.datasource.password
            valueFrom:
              configMapKeyRef:
                name: ptsagile-config
                key: spring.datasource.password
          - name: pts-service-registry
            valueFrom:
              configMapKeyRef:
                name: ptsagile-config
                key: pts-service-registry

---
apiVersion: v1
kind: Service
metadata:
  name: pts-service-registry
  namespace: pts-prod
spec:
   selector:
    app: pts-service-registry
   ports:
   - port: 8061
     protocol: TCP
     nodePort: 30000
     targetPort: 8061
   type: LoadBalancer 
