kind: ConfigMap
apiVersion: v1
metadata:
  name: ptsagile-config
  namespace: ptsagile-tentun
data:
  spring.datasource.url: jdbc:mysql://192.168.0.164:30012/${pts.database.schema-name}?createDatabaseIfNotExist=true&characterEncoding=UTF-8
  spring.datasource.password: root
  pts.log.path: /app/logs