apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: pts-registry-service
  namespace: ptsagile-tentun
spec:
  selector:
    matchLabels:
      app:  pts-registry-service
  replicas: 1
  template:
    metadata:
      labels:
        app: pts-registry-service
    spec:
      containers:
        - image:  {{DOCKER_IMAGE}}
          name: pts-registry-service
          ports:
           - containerPort: 8061
          env:
          - name: TZ
            value: Africa/Tunis
          - name: eureka.client.serviceUrl.defaultZone
            valueFrom:
              configMapKeyRef:
                name: pts-config
                key: eureka.client.service-url.defaultZone
          # - name: spring.datasource.url
          #   valueFrom:
          #     configMapKeyRef:
          #       name: ptsagile-config
          #       key: spring.datasource.url
          # - name: spring.datasource.username
          #   value: "root"
          # - name: spring.datasource.password
          #   valueFrom:
          #     configMapKeyRef:
          #       name: ptsagile-config
          #       key: spring.datasource.password
          - name: pts-registry-service
            valueFrom:
              configMapKeyRef:
                name: pts-config
                key: pts-registry-service

---
apiVersion: v1
kind: Service
metadata:
  name: pts-registry-service
  namespace: ptsagile-tentun
spec:
   selector:
    app: pts-registry-service
   ports:
   - port: 8061
     protocol: TCP
     nodePort: 30011
     targetPort: 8061
   type: LoadBalancer 
