FROM openjdk:8-jre-slim
# Set the working directory to /app
WORKDIR /app

# Copy the jarr files to the container
COPY ./pts-services-monorepo/service-registry/target/*.jar /app/service-registry.jar

# Expose port 8061
EXPOSE 8061

# Set the default command to run the application
CMD ["java", "-jar", "/app/service-registry.jar"]
